<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE email [
<!ELEMENT email (from,to,content)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT content (#PCDATA|exercises|person)*>
<!ELEMENT exercises (exercise*)>
<!ELEMENT exercise (topic, description)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT person (#PCDATA)>
]>
<email>
<from> abc@gmail.com </from>
<to> xyz@gmail.com </to>
<content>
<exercises>
<exercise>
<topic> DTD </topic>
<description> From Instance to DTD </description>
</exercise>
<exercise>
<topic> XSD</topic>
<description> From Instance to Schema</description>
</exercise>
</exercises>
Best Regards,
<person> ABC </person>
</content>
</email>
